# Generated by Django 3.2 on 2021-04-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_entry_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Topping',
        ),
    ]
