# Generated by Django 3.2 on 2021-05-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_comment_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
